num_classes: 1

# Training Configuration
training:

    batch_size: 2
    display_iters: 1
    iter_size: 10
    learning_rate: 0.0005

    # Dataset Configuration
    dataset:
        name: 'roads_dataset'
        params:
            root: '$DATASETS/spacenet'
            augmentations:
                - random_flip:
                - random_crop:
                      w: 600
                      h: 600

    # Model Configuration
    model:
        name: 'deeplabv3+'
        stride: 8

    tasks:
        binary_seg:
            loss: 'bce'

# Validation Configuration
validation:

    batch_size: 1
    val_epochs: 2

    # Dataset Configuration
    dataset:
        name: 'roads_dataset'
        params:
            training: False
            root: '$DATASETS/spacenet'

    metric:
        name: 'miou'
        params:
            task: 'binary_seg'
            num_classes: 2

    # Model Configuration
    model:
        name: 'deeplabv3+'
        stride: 8
