num_classes: 4

# Training Configuration
training:

    batch_size: 2
    display_iters: 1
    iter_size: 7
    learning_rate: 0.00025
    init: 'epoch_8.pth'

    # Dataset Configuration
    dataset:
        name: 'angle_detect_dataset'
        params:
            root: '/home/davidgj/projects/APR_TAX_RWY'
            augmentations:
                - pca:
                    sigma_pca: 0.05   
                - random_flip:
                - rotate:
                    sigma_angle: 17.0
                    w: 833
                    h: 417
    # Model Configuration
    model:
        name: 'deeplabv3+'
        stride: 8
        params:
          aux: False

    loss:
      - cross_entropy: 1.0

# Validation Configuration
validation:

    batch_size: 1
    val_epochs: 3

    val_expers:

        - name: "segmentation"
          # Dataset Configuration
          dataset:
            name: 'ori_dataset'
            params:
                root: '/home/davidgj/projects/APR_TAX_RWY'
                augmentations:
                    - pca:
                        sigma_pca: 0.05   
                    - random_flip:
                    - rotate:
                        sigma_angle: 17.0
                        w: 833
                        h: 417

          # Model Configuration
          model:
            name: 'deeplabv3+'
            stride: 8
            params:
              aux: False