num_classes: 1

# Training Configuration
training:

    batch_size: 1
    display_iters: 1
    iter_size: 10
    learning_rate: 0.0005

    # Dataset Configuration
    dataset:
        name: 'roads_dataset'
        params:
            root: '/home/davidgj/projects/refactor_v2/spacenet3'
            train_ori: False
            augmentations:
                - random_flip:
                - random_crop:
                    w: 700
                    h: 700

    # Model Configuration
    model:
        name: 'deeplabv3+'
        stride: 8

    loss:
       - lines_binary_seg: 1.0

# Validation Configuration
validation:

    batch_size: 1
    val_epochs: 4

    val_expers:

        - name: "line_seg"
          # Dataset Configuration
          dataset:
              name: 'roads_dataset'
              params:
                  training: False
                  root: '/home/davidgj/projects/refactor_v2/spacenet3'

          # Model Configuration
          model:
            name: 'deeplabv3+'
            stride: 8