num_classes: 1

# Training Configuration
training:

    batch_size: 1
    display_iters: 1
    iter_size: 10
    learning_rate: 0.0005

    # Dataset Configuration
    dataset:
        name: 'roads_dataset'
        params:
            root: '/home/davidgj/projects/refactor_v2/spacenet3'
            angle_step: 15.0
            augmentations:
                - random_flip:
                - random_crop:
                    w: 600
                    h: 600

    # Model Configuration
    model:
        name: 'roads_net_multitask'
        stride: 8
        params:
          angle_step: 15.0

    loss:
       - ori_binary_seg: 1.0
       - lines_binary_seg: 0.5

# Validation Configuration
validation:

    batch_size: 1
    val_epochs: 1

    val_expers:

        - name: "line_seg"
          # Dataset Configuration
          dataset:
              name: 'roads_dataset'
              params:
                  training: False
                  root: '/home/davidgj/projects/refactor_v2/spacenet3'

          # Model Configuration
          model:
              name: 'roads_net_stage1'
              stride: 8
              params:
                  angle_step: 15.0