num_classes: 1

# Training Configuration
training:

    batch_size: 1
    display_iters: 1
    iter_size: 10
    learning_rate: 0.0005

    # Dataset Configuration
    dataset:
        name: 'roads_dataset'
        params:
            root: '/home/davidgj/projects/refactor_v2/spacenet3'
            train_ori: False
            angle_step: 20.0
            augmentations:
                - random_flip:
                - random_crop:
                    w: 700
                    h: 700

    # Model Configuration
    model:
        name: 'roads_net_stage2_v2'
        stride: 8
        params:
          angle_step: 20.0

    loss:
       - binary_seg:
          name: 'bce'
          weight: 1.0

# Validation Configuration
validation:

    batch_size: 1
    val_epochs: 2

    # Dataset Configuration
    dataset:
        name: 'roads_dataset'
        params:
            training: False
            root: '/home/davidgj/projects/refactor_v2/spacenet3'

    metric:
      name: 'miou'
      params:
        key: 'binary_seg'
        num_classes: 2

    # Model Configuration
    model:
      name: 'roads_net'
      stride: 8
      params:
          angle_step: 20.0