num_classes: 1
training:
  batch_size: 1
  dataset:
    name: roads_dataset
    params:
      augmentations:
      - random_flip: null
      - random_crop:
          h: 700
          w: 700
      root: /home/davidgj/projects/refactor_v2/spacenet3
      train_ori: false
  display_iters: 1
  iter_size: 10
  learning_rate: 0.0005
  loss:
    binary_seg:
      loss_name: bce
      weight: 0.5
  model:
    name: deeplabv3+
    stride: 8
validation:
  batch_size: 1
  dataset:
    name: roads_dataset
    params:
      root: /home/davidgj/projects/refactor_v2/spacenet3
      training: false
  metric:
    name: miou
    params:
      num_classes: 2
      task_key: binary_seg
  model:
    name: deeplabv3+
    stride: 8
  val_epochs: 4
